[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

remappings = ["@openzeppelin=lib/openzeppelin-contracts",
    "@chainlink=lib/chainlink-brownie-contracts"
] 